/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NGODAO } from "./NGODAO";
export * as factories from "./factories";
export { NGODAO__factory } from "./factories/NGODAO__factory";
